---
driver:
  name: vagrant

platforms:
  - name: debian-8.11
  - name: ubuntu-18.04
  - name: centos-7.6
  - name: fedora-20

suites:
  - name: default
    run_list:
        - recipe[blackfire::mock]
        - recipe[blackfire]
    attributes:
        blackfire:
            agent:
                collector: 'http://127.0.0.1:8780'
                server_id: 'foo'
                server_token: 'bar'
                restart_mode: 'immediately'
